export enum _reduxConstant {
  DEVICELIST_REDUX = "ACT_00",
  DEVICELIST_SAGA = "ACT_01",
  DEVICE_SAGA = "ACT_02",
  DEVICELIST_DB_SAGA = "ACT_03",
  APPCTX_REDUX = "ACT_04",
  APPCTX_SAGA = "ACT_050-",
  APPCTX_DB_SAGA = "ACT_055",
  USER_REDUX = "ACT_06",
  BG_SERVICE_SAGA = "ACT_07",
  HB_DEVICELIST_REDUX = "ACT_08",
  HB_DEVICELIST_MSG_SENT = "ACT_09",
  HB_DEVICELIST_MSG_REC = "ACT_10",
  HB_SOCKET_LIST = "ACT_11",
  COLOR_UPDATE_SAGA = "ACT_12"

}